var languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log('languages array', languages);
var firstElement = languages[0];
console.log('The first element of the array:', firstElement);
var thirdElement = languages[2];
console.log('The third element of the array:', thirdElement);
var length = languages.length;
console.log('The length of the array is:', length);
var lastElement = languages[length - 1];
console.log('The last element in the array is:', lastElement);
